### ISSUE TITLE
Unstaged & Staged Changes tabs no longer autoclose after staging and commit

### ISSUE THREAD

**Issue by Kryten0807** [atom/github#1282]
### Prerequisites

* Have you tried to reproduce the problem in [Safe Mode][safe-mode]? **Yes**
* Have you followed all applicable steps in the [debugging guide][debugging-guide]? **Yes**
* Have you checked the FAQs on the [message board][message-board] for common solutions? **Yes**
* Have you checked that your issue [isn't already filed][already-filed]? **Yes**

### Description

I recently upgraded to address a different issue and found that the behaviour of the "Unstaged Changes" and "Staged Changes" tabs has changed.

I've come across a number of issues which may be related (see #1160 and #391 in particular), but none seem to address this change, which appears to have come about recently.

### Steps to Reproduce

Here's what I do and what I'm seeing:

1. edit a file & save it
    + *the file appears in the "Unstaged Changes" section of the Git Tab*
1. double-click the file in the "Unstaged Changes" section
    + *a new tab opens in the editor with the title "Unstaged Changes: path/to/file". It briefly contains the list of unstaged changes, then changes to "File has no contents"*
    + *the file appears in the "Staged Changes" section of the Git Tab.*
    + **Expectations** I expect the "Unstaged Changes: path/to/file" tab to close. This is what it used to do. Instead, I have to manually close the tab.
1. click the file in the "Stage Changes" section of the Git Tab
    + *the "Unstaged Changes" tab changes to "Staged Changes: path/to file". It contains the staged changes.*
1. add a commit message and press `Ctrl-Enter` to commit the change
    + *the "Staged Changes: path/to/file" tab becomes empty - it now says "File has no contents"
    + **Expectations** I expect the "Staged Changes: path/to/file" tab to close. This is what it used to do. Instead, I have to manually close the tab.

**Reproduces how often:**

This happens whenever I attempt to commit when using this version of Atom.

### Versions

OS: Kubuntu 14.04.4

Output of `atom --version`:

    Atom    : 1.23.3
    Electron: 1.6.15
    Chrome  : 56.0.2924.87
    Node    : 7.4.0

Output of `apm list`:

    Built-in Atom Packages (92)
    ├── atom-dark-syntax@0.28.0
    ├── atom-dark-ui@0.53.0
    ├── atom-light-syntax@0.29.0
    ├── atom-light-ui@0.46.0
    ├── base16-tomorrow-dark-theme@1.5.0
    ├── base16-tomorrow-light-theme@1.5.0
    ├── one-dark-ui@1.10.8
    ├── one-light-ui@1.10.8
    ├── one-dark-syntax@1.8.0
    ├── one-light-syntax@1.8.0
    ├── solarized-dark-syntax@1.1.2
    ├── solarized-light-syntax@1.1.2
    ├── about@1.7.8
    ├── archive-view@0.64.1
    ├── autocomplete-atom-api@0.10.5
    ├── autocomplete-css@0.17.4
    ├── autocomplete-html@0.8.3
    ├── autocomplete-plus@2.40.0
    ├── autocomplete-snippets@1.11.2
    ├── autoflow@0.29.0
    ├── autosave@0.24.6
    ├── background-tips@0.27.1
    ├── bookmarks@0.44.4
    ├── bracket-matcher@0.88.0
    ├── command-palette@0.42.0
    ├── dalek@0.2.1
    ├── deprecation-cop@0.56.9
    ├── dev-live-reload@0.47.1
    ├── encoding-selector@0.23.7
    ├── exception-reporting@0.42.0
    ├── find-and-replace@0.215.0
    ├── fuzzy-finder@1.7.3
    ├── github@0.8.3
    ├── git-diff@1.3.6
    ├── go-to-line@0.32.1
    ├── grammar-selector@0.49.8
    ├── image-view@0.62.4
    ├── incompatible-packages@0.27.3
    ├── keybinding-resolver@0.38.1
    ├── line-ending-selector@0.7.4
    ├── link@0.31.3
    ├── markdown-preview@0.159.18
    ├── metrics@1.2.6
    ├── notifications@0.69.2
    ├── open-on-github@1.3.1
    ├── package-generator@1.1.1
    ├── settings-view@0.253.1-0
    ├── snippets@1.1.9
    ├── spell-check@0.72.5
    ├── status-bar@1.8.14
    ├── styleguide@0.49.8
    ├── symbols-view@0.118.1
    ├── tabs@0.109.1
    ├── timecop@0.36.0
    ├── tree-view@0.221.3
    ├── update-package-dependencies@0.12.0
    ├── welcome@0.36.6
    ├── whitespace@0.37.5
    ├── wrap-guide@0.40.2 (disabled)
    ├── language-c@0.58.1
    ├── language-clojure@0.22.4
    ├── language-coffee-script@0.49.3
    ├── language-csharp@0.14.3
    ├── language-css@0.42.7
    ├── language-gfm@0.90.2
    ├── language-git@0.19.1
    ├── language-go@0.44.3
    ├── language-html@0.48.5
    ├── language-hyperlink@0.16.3
    ├── language-java@0.27.6
    ├── language-javascript@0.127.6
    ├── language-json@0.19.1
    ├── language-less@0.33.0
    ├── language-make@0.22.3
    ├── language-mustache@0.14.4
    ├── language-objective-c@0.15.1
    ├── language-perl@0.38.1
    ├── language-php@0.42.2
    ├── language-property-list@0.9.1
    ├── language-python@0.45.5
    ├── language-ruby@0.71.4
    ├── language-ruby-on-rails@0.25.2
    ├── language-sass@0.61.1
    ├── language-shellscript@0.25.4
    ├── language-source@0.9.0
    ├── language-sql@0.25.8
    ├── language-text@0.7.3
    ├── language-todo@0.29.3
    ├── language-toml@0.18.1
    ├── language-typescript@0.2.2
    ├── language-xml@0.35.2
    └── language-yaml@0.31.1

    Community Packages (16) /home/dthomas/.atom/packages
    ├── aligner@1.2.4
    ├── aligner-css@1.2.1
    ├── aligner-javascript@1.3.0
    ├── aligner-php@1.2.0
    ├── aligner-scss@1.3.1
    ├── atom-jade@0.3.0
    ├── busy-signal@1.4.3
    ├── docblockr@0.13.5
    ├── intentions@1.1.5
    ├── linter@2.2.0
    ├── linter-eslint@8.4.0
    ├── linter-ui-default@1.6.10
    ├── multi-wrap-guide@1.1.0
    ├── open-this@0.5.0
    ├── react@0.17.0
    └── sort-lines@0.18.0

**Comment by mrintegrity** [comment]
I would love to have this feature, it's quite annoying and interrupts my worḱflow to have to manually close the tab every time.

**Comment by nurtext** [comment]
It's been a while, but I'd like to know if this is getting fixed in the near future

**Comment by mediafinger** [comment]
Is there any other way to close empty tabs in Atom autoamtically? As not many people seem to be bothered by this behavior, maybe others are using a workaround?

**Comment by NRGLine4Sec** [comment]
any update on this ?

**Comment by agrossfield** [comment]
Problem still there, still annoying. Is there something we're all missing?

**Comment by adavie1** [comment]
I'll add voice to the chorus for fixing this.

**Comment by savetheclocktower** [comment]
I just started using the Git/GitHub integration in Atom after using an external GUI for years. Perhaps it's because I disabled pending pane items (as suggested in #1160), but this is also happening for me, and it's really annoying.

I should probably see if I can contribute a fix in PR form, but in the meantime, I came up with the workaround that @mediafinger was asking for.  Drop this into your init-script and it should automatically close these tabs when they become empty:

```js
const EmptyMonitor = {
  metaForElement: new Map(),
  observerOptions: {
    childList: false,
    attributes: true,
    subtree: false,
    attributeFilter: ['class']
  },

  setup () {
    this._observer = new MutationObserver(
      mutations => {
        for (let mutation of mutations) {
          let element = mutation.target;
          if (!element.classList.contains('github-FilePatchView--blank')) { return; }
          let { pane, item } = this.metaForElement.get(element);
          this.metaForElement.delete(element);
          pane.destroyItem(item);
        }
      }
    );
  },

  closeOnEmpty (item, pane) {
    if (!this._observer) { this.setup(); }
    let element = item.getElement().querySelector('.github-FilePatchView');
    if (!element) { return; }
    this.metaForElement.set(element, { item, pane });
    this._observer.observe(element, this.observerOptions);
  },

  observeIfFilePatchView (item, pane) {
    let uri = item.getURI();
    if (!uri || typeof uri !== 'string') { return false; }
    if (uri.startsWith('atom-github://file-patch/')) {
      this.closeOnEmpty(item, pane);
    }
  }
};

atom.workspace.observePanes(
  pane => {
    pane.onDidAddItem(({ item }) => {
      EmptyMonitor.observeIfFilePatchView(item, pane);
    });
  }
);
```

That ought to it for any new Atom windows; run the “Reload Window” command on any existing windows that you want to pick up this behavior.

I've played around with this workaround for ten minutes and tried to break it, but haven't been successful yet. If it doesn't work for you, see if there are any errors in your console (run the “Toggle Dev Tools” command) and let me know.

If you're an `init.coffee` person rather than `init.js`, I apologize.
