### ISSUE TITLE
Having this plugin running prohibits `rebase`

### ISSUE THREAD

**Issue by gjtorikian** [atom/github#792]
This is a bit odd. If Atom is running, with this package enabled, I can no longer run `git rebase` on the terminal. This is because apparently the package has held onto a Git lock:

```
fatal: Unable to create '/Users/gjtorikian/github/github/.git/index.lock': File exists.
Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.
```

As this package doesn't support `rebase -i`, dropping to the terminal is the only way to achieve this. Is there anything that can be done for this?

**Comment by BinaryMuse** [comment]
What's your current version? This should be fixed by https://github.com/atom/github/pull/726.

**Comment by BinaryMuse** [comment]
(You can use `git --git-dir ~/.atom/packages/github/.git rev-parse head` to get this for now)

**Comment by gjtorikian** [comment]
I think my version is mega old. I'm on f897a4c9a5b7fce0630d7088bbeb24979b666a35.

**Comment by gjtorikian** [comment]
Nope: I'm on ca87e3799492db2d559407f911bc32b540497809 now, and the problem persists. 😢

**Comment by BinaryMuse** [comment]
@gjtorikian Hm, curious. If you edit `~/.atom/packages/github/lib/models/workdir-context.js` and change the number `3000` on line 46 or so to something larger — say, `30000`, does the problem persist?

**Comment by gjtorikian** [comment]
I'm having trouble reproducing it now, so I'm wondering if I just forgot to restart Atom. 

Closing for now, then if it springs up again I'll try changing the timeout.
